"""Prompt composition for ALFWorld benchmark episodes."""

from __future__ import annotations

import json
from typing import Any

from homemaster.benchmarking.alfworld.translator import AlfworldCommandTranslator
from homemaster.benchmarking.alfworld.types import AlfworldEnvState, ObservationMode


def build_episode_prompt(
    *,
    state: AlfworldEnvState,
    translator: AlfworldCommandTranslator,
    memory_mode: str,
    max_invalid_actions: int,
    max_env_steps: int,
    observation_mode: ObservationMode = "visual_eval",
    subtask_instruction: str = "",
) -> str:
    action_reference = _format_action_reference(translator.public_action_schema())
    tool_choice_guidance = _format_tool_choice_guidance()
    memory_line = (
        "Memory tools are not available in this benchmark run."
        if memory_mode == "disabled"
        else f"Memory mode is {memory_mode}; use only the registered memory tools."
    )
    task_text = extract_task_text(state.task)
    # In long-horizon mode the operator-authored instruction is the primary
    # task description; the ALFWorld templated task_text is kept as a fallback.
    primary_task = subtask_instruction.strip() or task_text
    if observation_mode == "textual_debug":
        environment_json = json.dumps(
            state.to_model_visible_dict(),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        observation_lines = [
            (
                "Each tool result gives the latest observation, feedback, reward, "
                "done, won, and progress."
            ),
            (
                "If a tool fails, recover by choosing another tool call from the new "
                "observation and feedback."
            ),
            "Task and current environment:",
            environment_json,
        ]
    else:
        observation_lines = [
            "Use camera observations and available actions to complete the task.",
            "Tool results provide images and minimal execution status.",
            "Each robot action result image is the latest observation after that action.",
            "Inspect the latest image and success/error signal before choosing the next action.",
            (
                "Use task_progress_check only to record progress judgments supported "
                "by recent images or tool results."
            ),
            "Use robot_verify only to ask whether ALFWorld reports the full task as complete.",
            (
                "Infer task progress from camera images, tool success/error, and your "
                "own action history."
            ),
            "Task:",
            primary_task,
        ]
    long_horizon_note = (
        "This is one subtask in a chain; complete it, then stop. "
        "The next subtask will be given to you in the same scene — objects you "
        "moved stay where they are."
        if subtask_instruction.strip()
        else ""
    )
    return "\n".join(
        [
            "You are HomeMaster controlling a home assistant robot inside ALFWorld.",
            ("You must use tools to complete the task. Do not answer with raw ALFWorld commands."),
            (
                "Object and receptacle names should match the current environment "
                "language when possible."
            ),
            "Success is determined only by ALFWorld won=true, not by a verbal completion claim.",
            f"The episode fails after {max_env_steps} ALFWorld environment action steps.",
            f"The episode fails if invalid action count reaches {max_invalid_actions}.",
            memory_line,
            long_horizon_note,
            "",
            "Tool choice guidance:",
            tool_choice_guidance,
            "",
            *observation_lines,
            "",
            "Action reference generated by the environment translator:",
            action_reference,
        ]
    )


def extract_task_text(task: str) -> str:
    marker = "Your task is to:"
    for line in reversed(task.splitlines()):
        if marker in line:
            return line.strip()
    stripped = task.strip()
    return stripped if stripped else "Complete the current task."


def _format_action_reference(schema: dict[str, Any]) -> str:
    lines = [f"Environment: {schema['environment']}"]
    navigation = schema.get("navigation")
    if isinstance(navigation, dict):
        lines.append("Navigation form:")
        lines.append(f"- {navigation['command_template']}")
    manipulation = schema.get("manipulation_actions", [])
    if manipulation:
        lines.append("Manipulation forms:")
        for item in manipulation:
            required = ", ".join(item.get("required", []))
            line = f"- action={item['action']}, required=[{required}]: {item['command_template']}"
            notes = item.get("notes")
            if isinstance(notes, str) and notes:
                line += f" ({notes})"
            lines.append(line)
    return "\n".join(lines)


def _format_tool_choice_guidance() -> str:
    return "\n".join(
        [
            (
                "- Use robot_go_to for any target you need to approach: movable objects, "
                "receptacles, furniture, appliances, containers, and switch/toggle objects."
            ),
            (
                "- Do not guess many source locations or ALFWorld navigation names. If you "
                "need an object, place, tool, or container, call robot_go_to with that target."
            ),
            (
                "- Reuse robot_go_to's returned target label, object label, and source "
                "receptacle in later manipulation calls when they are provided."
            ),
        ]
    )
