"""Prompt composition for ALFWorld benchmark episodes."""

from __future__ import annotations

import json
from typing import Any

from homemaster.benchmarking.alfworld.translator import AlfworldCommandTranslator
from homemaster.benchmarking.alfworld.types import AlfworldEnvState


def build_episode_prompt(
    *,
    state: AlfworldEnvState,
    translator: AlfworldCommandTranslator,
    memory_mode: str,
    max_invalid_actions: int,
    max_env_steps: int,
) -> str:
    action_reference = _format_action_reference(translator.public_action_schema())
    memory_line = (
        "Memory tools are not available in this benchmark run."
        if memory_mode == "disabled"
        else f"Memory mode is {memory_mode}; use only the registered memory tools."
    )
    environment_json = json.dumps(
        state.to_model_visible_dict(),
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    )
    return "\n".join([
        "You are HomeMaster controlling a home assistant robot inside ALFWorld.",
        "You must use tools to complete the task. Do not answer with raw ALFWorld commands.",
        "Object and receptacle names should match the current environment language when possible.",
        "Each tool result gives the latest observation, feedback, reward, done, won, and progress.",
        (
            "If a tool fails, recover by choosing another tool call from the new "
            "observation and feedback."
        ),
        "Success is determined only by ALFWorld won=true, not by a verbal completion claim.",
        f"The episode fails after {max_env_steps} ALFWorld environment action steps.",
        f"The episode fails if invalid action count reaches {max_invalid_actions}.",
        memory_line,
        "",
        "Action reference generated by the environment translator:",
        action_reference,
        "",
        "Task and current environment:",
        environment_json,
    ])


def _format_action_reference(schema: dict[str, Any]) -> str:
    lines = [f"Environment: {schema['environment']}"]
    observe = schema.get("observe_modes", [])
    if observe:
        lines.append("Observation forms:")
        for item in observe:
            lines.append(f"- mode={item['mode']}: {item['command_template']}")
    navigation = schema.get("navigation")
    if isinstance(navigation, dict):
        lines.append("Navigation form:")
        lines.append(f"- {navigation['command_template']}")
    manipulation = schema.get("manipulation_actions", [])
    if manipulation:
        lines.append("Manipulation forms:")
        for item in manipulation:
            required = ", ".join(item.get("required", []))
            line = (
                f"- action={item['action']}, required=[{required}]: "
                f"{item['command_template']}"
            )
            notes = item.get("notes")
            if isinstance(notes, str) and notes:
                line += f" ({notes})"
            lines.append(line)
    return "\n".join(lines)
